version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: brainstormer-frontend-local
    ports:
      - '3000:80' # Map host port 3000 to container port 80 (Nginx in frontend container)
    networks:
      - brainstormer-net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: brainstormer-backend-local
    env_file:
      - .env
    volumes:
      - ./.env:/code/.env:ro
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    # Port exposure is handled by nginx, no need to map to host directly for local test via nginx
    # ports:
    #   - "${PORT}:${PORT}"
    networks:
      - brainstormer-net
    depends_on:
      - redis

  nginx:
    image: nginx:stable-alpine
    container_name: brainstormer-nginx-local
    ports:
      - '8000:8000' # Map host port 8080 to container port 80 (Nginx reverse proxy)
    volumes:
      - ./docker/nginx/local.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/.htpasswd:/etc/nginx/.htpasswd:ro # Mount the password file
    depends_on:
      - frontend
      - backend
    networks:
      - brainstormer-net

  redis:
    image: redis:alpine
    container_name: brainstormer-redis-local
    volumes:
      - redis-data-local:/data
    networks:
      - brainstormer-net

networks:
  brainstormer-net:
    driver: bridge

volumes:
  redis-data-local:
