version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: brainstormer-frontend
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /etc/letsencrypt:/etc/nginx/ssl:ro
      - ./docker/.htpasswd:/etc/nginx/.htpasswd:ro
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: brainstormer-backend
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
