export const searchResultsMock = [
  'Thunder',
  'Tempest',
  'Lightning',
  'Hurricane',
  'Tornado',
  'Typhoon',
  'Deluge',
  'Cyclone',
  'Gale force',
  'Downpour',
  'Flash flood',
  'Hailstorm',
  'Blizzard',
  'Squall',
  'Monsoon',
  'Eye of the storm',
  'Thunderstorm',
  'Whirlwind',
  'Microburst',
  'Waterspout',
  'Lightning strike',
  'Storm surge',
  'Wind shear',
  'Atmospheric pressure',
  'Precipitation',
  'Doppler radar',
  'Squall line',
  'Barometric pressure',
  'Power outage',
  'Storm cloud',
  'Supercell',
  'Flood warning',
  'Cold front',
  'Heat lightning',
  'Electrical discharge',
  'Tornadic activity',
  'Anvil cloud',
  'Jet stream',
  'Wind gusts',
  'Storm tracker',
  'Weather satellite',
  'Cumulonimbus',
  'Funnel cloud',
  'Vortex formation',
  'Lightning rod',
  'Low pressure system',
  'Cloudburst',
  'Thunderhead',
  'Coriolis effect',
  'Barometric reading',
  'Polar vortex',
  'Meteorology',
  'Thunderclap',
  'Stormwater runoff',
  'Climate change',
  'Tropical depression',
  'Flash flooding',
  'Windstorm',
  'Watershed',
  'Forecasting',
  'Cloud seeding',
  'Static electricity',
  'Updraft',
  'Haboob',
  'Sleet',
  'Storm damage',
  'Tornado warning',
  'Tornadic winds',
  'Cloud formation',
  'Cold front collision',
  'Temperature inversion',
  'Earthquake storm',
  'Meteorological phenomena',
  'Lightning bolt',
  'Storm chaser',
  'Rain gauge',
  'Anemometer',
  'Power grid failure',
  'Convection cell',
  'Seismic storm',
  'Lightning flash',
  'Thermodynamic instability',
  'Vortex ring',
  'Wind chill',
  'Evaporation',
  'Pressure system',
  'Storm preparation',
  'Seiche',
  'Monsoon rains',
  'Hydrology',
  'Wind tunnel',
  'Fluctuating pressure',
  'Occlusion',
  'Isobaric lines',
  'Pre-storm conditions',
  'Radial wind',
  'Heatwave',
  'Drought',
  'Rising temperatures',
  'Polar front',
  'Doppler shift',
  'Geostrophic wind',
  'Downburst',
  'Catastrophic storm',
  'Severe weather',
  'Storm surge protection',
  'Low pressure front',
]
