export const searchResultsMock = [
  'Trees',
  'Endangered species',
  'Canopy',
  'Moss',
  'Natural disasters',
  'Ecosystem',
  'Exploration',
  'Roots',
  'Timber',
  'Hunters and gatherers',
  'Predators',
  'Moths',
  'Survival',
  'Fern-covered trails',
  'Rainfall',
  'Park ranger station',
  'Mushrooms',
  'Erosion',
  'Trails',
  'Underground networks',
  'Oxygen',
  'Fog',
  'Campfire',
  'Predators and prey',
  'Deforestation',
  'Logging',
  'Insects',
  'Soil',
  'Fairy tales',
  'Photography',
  'Bioluminescence',
  'Undergrowth',
  'Scavengers',
  'Fungi',
  'Druids',
  'Bushcraft',
  'Scent',
  'Solitude',
  'Camouflage',
  'National parks',
  'Wolves',
  'Timberwolves',
  'Wilderness',
  'Foliage',
  'Evergreen',
  'Deciduous',
  'Ancient groves',
  'Biodiversity',
  'Photosynthesis',
  'Carbon sequestration',
  'Wildlife corridors',
  'Bark',
  'Sap',
  'Dappled light',
  'Trekking',
  'Forest bathing',
  'Symbiosis',
  'Nurse logs',
  'Forest floor',
  'Decomposition',
  'Mycorrhizal networks',
  'Pine',
  'Oak',
  'Redwood',
  'Ferns',
  'Lichen',
  'Birdsong',
  'Ecological succession',
  'Forest management',
  'Foraging',
  'Wildfires',
  'Fire ecology',
  'Forest spirits',
  'Charcoal',
  'Sustainability',
  'Wood carving',
  'Enchanted forest',
  'Dryads',
  'Forest therapy',
  'Old-growth forest',
  'Tree rings',
  'Habitat destruction',
  'Reforestation',
  'Shadow patterns',
  'Dew',
  'Mist',
  'Seasonal changes',
  'Forest fruits',
  'Maple syrup',
  'Medicinal plants',
  'Indigenous knowledge',
  'Cryptozoology',
  'Forest reserves',
  'Lumber industry',
  'Paper production',
  'Arborists',
  'Treetop canopy walks',
  'Folklore',
  'Green lungs',
  'Nest',
  'Hollow trees',
  'Clearings',
  'Forest edge',
  'Wildflowers',
  'Seedlings',
  'Tree identification',
  'Wilderness survival',
  'Deadfall',
  'Animal tracks',
  'Forest conservation',
  'Woodpeckers',
  'Owls',
  'Nocturnal creatures',
  'Carbon cycle',
  'Climate regulation',
  'Nordic forests',
  'Tropical rainforests',
  'Boreal forests',
  'Coniferous',
  'Broadleaf',
  'Temperate forests',
  'Forest densities',
  'Sylvan',
  'Tree hugging',
  'Natural remedies',
  'Forest soundscapes',
  'Leaves',
  'Canopy research',
  'Biological diversity',
  'Forest-dwelling cultures',
  'Wildcraft',
  'Treehouse',
  'Animal migration',
  'Forest regeneration',
  'Woodland',
  'Sacred groves',
  'Forest product design',
  'Biomes',
  'Morning dew',
  'Ecotourism',
  'Ancient wisdom',
  'Forestry science',
  'Winter forest',
  'Sunlit glades',
  'Forest canopy bridges',
  'Pine needles',
  'Felled trees',
  'Forest service',
  'Herbivores',
  'Carnivores',
  'Acorns',
  'Seeds dispersal',
  'Natural selection',
  'Wilderness literature',
  'Mythology',
  'Forest microclimates',
  'Primeval',
  'Timberland',
  'Jungle',
  'Woodlands',
  'Habitat restoration',
  'Timber harvesting',
  'Forest ecosystems',
  'Root systems',
  'Biomimicry',
  'Traditional forestry',
  'Silent woods',
  'Towering pines',
  'Forest resilience',
  'Watershed protection',
  'Orchids',
  'Rustic cabins',
  'Endangered habitats',
  'Ecological balance',
  'Biogeochemical cycles',
  'Forest stewardship',
  'Permaculture',
  'Forest gardening',
  'Adaptive management',
  'Branch',
  'Moss-covered stones',
  'Glacial remnants',
  'Alpine forests',
  'Cloud forests',
  'Dripping canopies',
  'Leaf litter',
  'Mulch',
  'Forest soil health',
  'Wildlife photography',
  'Bird watching',
  'Forest cartography',
  'Historical logging',
  'Indigenous territories',
  'Forest communities',
  'Shade tolerance',
  'Natural repellents',
  'Forestry tools',
  'Wood processing',
  'Forest fragmentation',
  'Biodiversity hotspots',
  'Genetic diversity',
  'Forest infrastructure',
  'Recreation',
  'Epiphytes',
  'Nutrient cycling',
  'Forest geology',
]
